apiVersion: skaffold/v4beta1
kind: Config
build:
  googleCloudBuild:
    projectId: ticketing-dev-370913
  artifacts:
  - image: us.gcr.io/ticketing-dev-370913/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}

